# Generated by Django 4.2 on 2025-04-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Меню')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения меню на странице')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок элемента меню')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Прямой URL для пункта меню')),
                ('named_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имнованный URL для пункта меню')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения элемента внутри своего уровня вложенности')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='unique_item_for_parent'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(check=models.Q(('id', models.F('parent')), _negated=True), name='not_self_parent'),
        ),
    ]
